//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vle-webservices.lsvle.pre.det.nsw.edu.au/UserInformation.asmx")]
        public string Doe_Ls_SampleProject_Core_VleWsUserInformation_UserInformation {
            get {
                return ((string)(this["Doe_Ls_SampleProject_Core_VleWsUserInformation_UserInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://applogger.lsvle.pre.det.nsw.edu.au/webservices/CilLoggerService.asmx")]
        public string Doe_Ls_SampleProject_Core_VleWsLoggerService_CilLoggerService {
            get {
                return ((string)(this["Doe_Ls_SampleProject_Core_VleWsLoggerService_CilLoggerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ssoaddons.det.nsw.edu.au/paservice/services/PartnerApp")]
        public string Doe_Ls_SchoolSportsUnit_Core_PartnerAppWs_PartnerAppService {
            get {
                return ((string)(this["Doe_Ls_SchoolSportsUnit_Core_PartnerAppWs_PartnerAppService"]));
            }
        }
    }
}
