// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Doe.Ls.ProjectTemplate.Data.T4Templates._archived
{
    using Doe.Ls.EntityBase.Helper;
    using System.Data.Entity.Core.Metadata.Edm;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class temp_1_single_view_partial_update : MVCTemplate.BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 12 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
 T4Helper.SetAssemblyClassNameFormatFromContext(EntityContext); 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
    var helper=new EdmMetadataHelper(EntityContext);
    if(this.EntityType.Name=="GeneralLog"){
    } 

            
            #line default
            #line hidden
            this.Write("@using Doe.Ls.EntityBase.MVCExtensions\r\n@model ");
            
            #line 20 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write(@"
@{
    var user = ViewBagWrapper.UserInfoExtensionBag.GetCurrentUser(ViewData);
    var task = ViewBagWrapper.TaskBag.GetCurrentTask(ViewData); 
    var formMethod = ViewBagWrapper.FormOperations.GetFormMethod(ViewData);
    
    var formType = ViewBagWrapper.FormOperations.GetFormType(ViewData);
    var requestType = ViewBagWrapper.FormOperations.GetRequestType(ViewData);
    ");
            
            #line 28 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
 var lookups=new List<string>();
  var suffix="";
    
   
            
            #line default
            #line hidden
            
            #line 32 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
foreach (var mp in T4Helper.ListPropertiesWithFkInfo(EntityType)){
if(!mp.FK)continue;
        var parentItemName=T4Helper.GetLocalVariableName(mp.PareEntityType);
        if(lookups.Contains(parentItemName)){suffix=string.Format("{0}",lookups.IndexOf(parentItemName));}else{
        lookups.Add(parentItemName);
        }
        var localVariableName= T4Helper.GetLocalVariableName(mp.PareEntityType)+"Items"+suffix;

            
            #line default
            #line hidden
            this.Write("    var ");
            
            #line 40 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localVariableName));
            
            #line default
            #line hidden
            this.Write(" = ViewBagWrapper.ListBag.GetList(\"");
            
            #line 40 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localVariableName));
            
            #line default
            #line hidden
            this.Write("\",ViewData);\r\n");
            
            #line 41 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
    } 
            
            #line default
            #line hidden
            this.Write("    \r\n}\r\n\r\n@Html.AntiForgeryToken()\r\n\r\n");
            
            #line 46 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
    foreach (var pm in T4Helper.ListPropertiesWithFkInfo(EntityType))    
            
            #line default
            #line hidden
            
            #line 47 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
    { 
            
            #line default
            #line hidden
            
            #line 48 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        if(T4Helper.PropertyOperations.IsKey(pm.Property,EntityType) && T4Helper.PropertyOperations.IsKeyAutoIncrement(EntityType,EntityContext))
            
            #line default
            #line hidden
            
            #line 49 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        {
            
            #line default
            #line hidden
            this.Write(" \r\n@Html.HiddenFor(model => model.");
            
            #line 50 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n@if(formType==FormType.Edit)  {\r\n    <div class=\"form-group @GetFormGroupClass" +
                    "(\"");
            
            #line 52 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\")\">\r\n        <label class=\"col-lg-4 \">@Html.DisplayNameFor(model => model.");
            
            #line 53 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write(") </label>\r\n        <div class=\"col-lg-8\">            <p class=\"form-control-plai" +
                    "ntext\">@Html.DisplayFor(model => model.");
            
            #line 54 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write(")</p>        </div>\r\n    </div>                       \r\n}\r\n");
            
            #line 57 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            continue;
            
            #line default
            #line hidden
            
            #line 58 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        }/*IsKey*/         
            
            #line default
            #line hidden
            
            #line 59 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        if (!T4Helper.PropertyOperations.IsCheckbox(pm.Property)) {
            
            #line default
            #line hidden
            this.Write("<div class=\"form-group @GetFormGroupClass(\"");
            
            #line 60 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\")\">\r\n");
            
            #line 61 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
if (pm.FK) 
            
            #line default
            #line hidden
            
            #line 62 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            { 
            
            #line default
            #line hidden
            this.Write(" <label for=\"");
            
            #line 63 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" class=\"col-lg-4\">@Html.DisplayNameFor(model => model.");
            
            #line 63 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.PareEntityType.Name));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 63 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAsteriskForRequiredField(pm.Property)));
            
            #line default
            #line hidden
            this.Write("</label>\r\n");
            
            #line 64 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            }/*is !FK*/else{ 
            
            #line default
            #line hidden
            this.Write("<label for=\"");
            
            #line 64 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" class=\"col-lg-4\">@Html.DisplayNameFor(model => model.");
            
            #line 64 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 64 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAsteriskForRequiredField(pm.Property)));
            
            #line default
            #line hidden
            this.Write("</label>\r\n    ");
            
            #line 65 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
}/*not FK*/ 
            
            #line default
            #line hidden
            
            #line 66 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            if (!pm.FK){ 
            
            #line default
            #line hidden
            
            #line 67 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            } else {
            
            #line default
            #line hidden
            
            #line 68 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            } 
            
            #line default
            #line hidden
            
            #line 69 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            if (!pm.FK){ 
            
            #line default
            #line hidden
            this.Write("            \r\n");
            
            #line 70 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            if (!pm.FK&&T4Helper.IsFormInput(pm.Property,EntityType,EntityContext)){ 
            
            #line default
            #line hidden
            this.Write(" <input type=\"");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputType(pm.Property)));
            
            #line default
            #line hidden
            this.Write("\" name=\"");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" id=\"");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" class=\"form-control col-lg-8\" placeholder=\"e.g. ");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.Wordify(pm.Property.Name)));
            
            #line default
            #line hidden
            this.Write("\" value=\"@Model.");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\"@ReadOnly(\"");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\")  ");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(IsRequired(pm.Property)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SetEmail(pm.Property)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SetDate(pm.Property)));
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 71 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SetInteger(pm.Property)));
            
            #line default
            #line hidden
            this.Write(" />\r\n");
            
            #line 72 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            } 
            
            #line default
            #line hidden
            
            #line 73 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            if (!pm.FK&&T4Helper.PropertyOperations.IsTextArea(pm.Property,EntityType,EntityContext))
            
            #line default
            #line hidden
            
            #line 74 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            { 
            
            #line default
            #line hidden
            this.Write(" <textarea name=\"");
            
            #line 75 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" id=\"");
            
            #line 75 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" class=\"form-control col-lg-8 ");
            
            #line 75 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.PropertyOperations.IsRichText(pm.Property,EntityType)?"tinymce":string.Empty));
            
            #line default
            #line hidden
            this.Write("\" placeholder=\"e.g. ");
            
            #line 75 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.Wordify(pm.Property.Name)));
            
            #line default
            #line hidden
            this.Write("\" ");
            
            #line 75 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SetRichText(pm.Property)));
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 75 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(IsRequired(pm.Property)));
            
            #line default
            #line hidden
            this.Write("  >@Model.");
            
            #line 75 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("</textarea>\r\n");
            
            #line 76 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            } 
            
            #line default
            #line hidden
            
            #line 77 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            if (!pm.FK)
            
            #line default
            #line hidden
            
            #line 78 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            { 
            
            #line default
            #line hidden
            this.Write("                       \r\n");
            
            #line 79 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            } 
            
            #line default
            #line hidden
            
            #line 80 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            if (pm.FK) 
            
            #line default
            #line hidden
            
            #line 81 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            { 
            
            #line default
            #line hidden
            this.Write(" @Html.DropDownList(\"");
            
            #line 82 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 82 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(pm.PareEntityType)));
            
            #line default
            #line hidden
            this.Write("Items , \"Select ");
            
            #line 82 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.PareEntityType.Name.Wordify()));
            
            #line default
            #line hidden
            this.Write(" ...\", new {id=\"");
            
            #line 82 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\", @class = \"form-control col-lg-8 select2picker\"");
            
            #line 82 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRequiredPropertyValue(pm.Property)));
            
            #line default
            #line hidden
            this.Write(" })      \r\n");
            
            #line 83 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            } 
            
            #line default
            #line hidden
            this.Write("    \r\n</div>  \r\n                     \r\n");
            
            #line 86 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        } 
            
            #line default
            #line hidden
            
            #line 87 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        } /*not checkbox*/ 
            
            #line default
            #line hidden
            this.Write("\r\n ");
            
            #line 89 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        if (T4Helper.PropertyOperations.IsCheckbox(pm.Property))
            
            #line default
            #line hidden
            
            #line 90 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        { 
            
            #line default
            #line hidden
            this.Write("        <div class=\"form-check\">\r\n            <label class=\"form-check-label\">\r\n " +
                    "               <input class=\"form-check-input\"  type=\"checkbox\" name=\"");
            
            #line 93 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" id=\"");
            
            #line 93 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" checked=\"@Model.");
            
            #line 93 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\" @ReadOnly(\"");
            
            #line 93 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));
            
            #line default
            #line hidden
            this.Write("\")/>\r\n            </label>\r\n        </div>    \r\n");
            
            #line 96 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
        } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 98 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
    }/*foreach*/ 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n@functions\r\n{\r\n    bool IsKey(string propertyName) \r\n    {\r\n        var entit" +
                    "yType = ViewBagWrapper.EntityInfo.GetEntityType(ViewData);\r\n        return T4Hel" +
                    "per.GetKeys(entityType).Any(p => p.Name == propertyName);\r\n    }\r\n\r\n    string R" +
                    "eadOnly(string propertyName) \r\n    {\r\n        var formType = ViewBagWrapper.Form" +
                    "Operations.GetFormType(ViewData);\r\n        if (formType == FormType.Edit && IsKe" +
                    "y(propertyName)) return \"readonly\";\r\n\r\n        var entityType = ViewBagWrapper.E" +
                    "ntityInfo.GetEntityType(ViewData);\r\n        \r\n        var prop = T4Helper.GetPro" +
                    "perty(propertyName, entityType);\r\n        var computedAttribute = T4Helper.Metad" +
                    "ataOperations.GetMetadataPropertyCustomAttribute<ComputedPropertyAttribute>(prop" +
                    ", entityType);\r\n        if (computedAttribute == null) return string.Empty;\r\n\r\n " +
                    "       if (computedAttribute.ComputedPropertyType == ComputedPropertyType.LastMo" +
                    "difiedDate) return \"readonly\";\r\n        if (computedAttribute.ComputedPropertyTy" +
                    "pe == ComputedPropertyType.LastModifiedUser) return \"readonly\";\r\n\r\n        if (c" +
                    "omputedAttribute.ComputedPropertyType == ComputedPropertyType.CreationDate) retu" +
                    "rn \"readonly\";\r\n        if (computedAttribute.ComputedPropertyType == ComputedPr" +
                    "opertyType.CreatedUser) return \"readonly\";\r\n        \r\n        return string.Empt" +
                    "y;\r\n    }\r\n\r\n    string GetFormGroupClass(string propertyName) \r\n    {\r\n        " +
                    "var entityType = ViewBagWrapper.EntityInfo.GetEntityType(ViewData);\r\n        var" +
                    " formType = ViewBagWrapper.FormOperations.GetFormType(ViewData);\r\n        var pr" +
                    "op = T4Helper.GetProperty(propertyName, entityType);\r\n        var computedAttrib" +
                    "ute = T4Helper.MetadataOperations.GetMetadataPropertyCustomAttribute<ComputedPro" +
                    "pertyAttribute>(prop, entityType);\r\n        if (computedAttribute == null) retur" +
                    "n string.Empty;\r\n\r\n        if (computedAttribute.ComputedPropertyType == Compute" +
                    "dPropertyType.LastModifiedDate) return \"hidden\";\r\n        if (computedAttribute." +
                    "ComputedPropertyType == ComputedPropertyType.LastModifiedUser) return \"hidden\";\r" +
                    "\n\r\n        if (computedAttribute.ComputedPropertyType == ComputedPropertyType.Cr" +
                    "eationDate) return \"hidden\";\r\n        if (computedAttribute.ComputedPropertyType" +
                    " == ComputedPropertyType.CreatedUser) return \"hidden\";\r\n\r\n        switch (formTy" +
                    "pe)\r\n        {\r\n            case FormType.Create:\r\n            {\r\n              " +
                    "  if (computedAttribute.ComputedPropertyType == ComputedPropertyType.Status) ret" +
                    "urn \"hidden\";\r\n                if (computedAttribute.ComputedPropertyType == Com" +
                    "putedPropertyType.AutoIncrement) return \"hidden\";\r\n                if (computedA" +
                    "ttribute.ComputedPropertyType == ComputedPropertyType.Computed) return \"hidden\";" +
                    "\r\n                break;\r\n            }\r\n        }\r\n        return string.Empty;" +
                    "        \r\n    }    \r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 156 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"

    void GenerateAddonSpan(EdmProperty property)
    {
    if(!T4Helper.PropertyOperations.IsRichText(property,EntityType))
        {
            
        
        #line default
        #line hidden
        
        #line 161 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"
this.Write("          \r\n        ");

        
        #line default
        #line hidden
        
        #line 162 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"

        }
    }

        
        #line default
        #line hidden
        
        #line 167 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"


    private string  IsRequired(EdmProperty property)
    {
        return T4Helper.PropertyOperations.IsRequired(property, EntityType, EntityContext)
            ? "required data-fv-notempty-message='The " + T4Helper.Wordify(property.Name) + " is required'"
            : "";


    }


        
        #line default
        #line hidden
        
        #line 180 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"


    private string  GetRequiredPropertyValue(EdmProperty property)
    {
        return T4Helper.PropertyOperations.IsRequired(property, EntityType, EntityContext)
            ? ", Required=\"Required\"": "";
            
    }


        
        #line default
        #line hidden
        
        #line 191 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"

	private string GetAsteriskForRequiredField(EdmProperty property)
	{
		return T4Helper.PropertyOperations.IsRequired(property, EntityType, EntityContext) ? "<span class=\"mandatory\">*</span>" : "";
	}

        
        #line default
        #line hidden
        
        #line 198 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"


    private string  SetRichText(EdmProperty property)
    {
        return T4Helper.PropertyOperations.IsRichText(property, EntityType)
            ? "data-role-rich='rich-text'"
            : string.Empty;


    }


        
        #line default
        #line hidden
        
        #line 211 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"


    private string  SetEmail(EdmProperty property)
    {
        return T4Helper.PropertyOperations.IsEmail(property)
            ? "data-fv-emailaddress-message='The " + T4Helper.Wordify(property.Name) + " is not correct email format'"
            : "";


    }


        
        #line default
        #line hidden
        
        #line 224 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"


    private string  SetDate(EdmProperty property)
    {
        return T4Helper.PropertyOperations.IsDate(property) || T4Helper.PropertyOperations.IsDateTime(property)
            ? "data-fv-date-format=\"DD/MM/YYYY\""
            : "";
            }


        
        #line default
        #line hidden
        
        #line 235 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"


    private string GetInputType(EdmProperty property)
    {
        return T4Helper.GetInputType(property, EntityType, EntityContext);
    }


        
        #line default
        #line hidden
        
        #line 246 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"


    private string SetInteger(EdmProperty property)
    {
        return T4Helper.PropertyOperations.IsInteger(property)
            ? "data-fv-integer-message='The " + T4Helper.Wordify(property.Name) + " is not an integer'"
            : "";
    }


        
        #line default
        #line hidden
        
        #line 1 "C:\Projects\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\_archived\temp_1_single_view_partial_update.tt"

private string _AppNamespaceField;

/// <summary>
/// Access the AppNamespace parameter of the template.
/// </summary>
private string AppNamespace
{
    get
    {
        return this._AppNamespaceField;
    }
}

private global::System.Data.Entity.DbContext _EntityContextField;

/// <summary>
/// Access the EntityContext parameter of the template.
/// </summary>
private global::System.Data.Entity.DbContext EntityContext
{
    get
    {
        return this._EntityContextField;
    }
}

private global::System.Data.Entity.Core.Metadata.Edm.EntityType _EntityTypeField;

/// <summary>
/// Access the EntityType parameter of the template.
/// </summary>
private global::System.Data.Entity.Core.Metadata.Edm.EntityType EntityType
{
    get
    {
        return this._EntityTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool AppNamespaceValueAcquired = false;
if (this.Session.ContainsKey("AppNamespace"))
{
    this._AppNamespaceField = ((string)(this.Session["AppNamespace"]));
    AppNamespaceValueAcquired = true;
}
if ((AppNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AppNamespace");
    if ((data != null))
    {
        this._AppNamespaceField = ((string)(data));
    }
}
bool EntityContextValueAcquired = false;
if (this.Session.ContainsKey("EntityContext"))
{
    this._EntityContextField = ((global::System.Data.Entity.DbContext)(this.Session["EntityContext"]));
    EntityContextValueAcquired = true;
}
if ((EntityContextValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityContext");
    if ((data != null))
    {
        this._EntityContextField = ((global::System.Data.Entity.DbContext)(data));
    }
}
bool EntityTypeValueAcquired = false;
if (this.Session.ContainsKey("EntityType"))
{
    this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(this.Session["EntityType"]));
    EntityTypeValueAcquired = true;
}
if ((EntityTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityType");
    if ((data != null))
    {
        this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
