//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEntityType
    {
        public int EntityTypeId { get; set; }
        public string EntityApiName { get; set; }
        public string EntityTitle { get; set; }
        public string EntityDescription { get; set; }
        public bool SysAdminDashboard { get; set; }
        public bool PowerUserDashboard { get; set; }
        public bool HighPriority { get; set; }
    }
}
