//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppObjectInfo
    {
        public string ObjectName { get; set; }
        public Nullable<int> CounterValue { get; set; }
        public Nullable<double> AggregatedValueA { get; set; }
        public Nullable<double> AggregatedValueB { get; set; }
        public string Metadata { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string lastModifiedUser { get; set; }
    }
}
