//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCentreDetail
    {
        public int PositionId { get; set; }
        public string CostCentre { get; set; }
        public string Fund { get; set; }
        public string PayrollWBS { get; set; }
        public string RCCJDEPayrollCode { get; set; }
        public string GLAccount { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
