//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSetting
    {
        public int SettingsKey { get; set; }
        public string PropertyCode { get; set; }
        public Nullable<bool> PropertyBooleanValue { get; set; }
        public string PropertyValue { get; set; }
        public string EntityContextCode { get; set; }
        public string EntityContextValue { get; set; }
        public string Tag { get; set; }
    }
}
