//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyRelationship
    {
        public int KeyRelationshipId { get; set; }
        public int RoleDescriptionId { get; set; }
        public Nullable<int> ScopeId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Who { get; set; }
        public string Why { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifiedUserName { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual RelationshipScope RelationshipScope { get; set; }
        public virtual RoleDescription RoleDescription { get; set; }
    }
}
