//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupFocusGradeCriteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupFocusGradeCriteria()
        {
            this.PositionFocusCriterias = new HashSet<PositionFocusCriteria>();
        }
    
        public int LookupId { get; set; }
        public int FocusId { get; set; }
        public string GradeCode { get; set; }
        public int SelectionCriteriaId { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool IsMandatory { get; set; }
    
        public virtual Focus Focus { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual SelectionCriteria SelectionCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionFocusCriteria> PositionFocusCriterias { get; set; }
    }
}
