//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionHistory
    {
        public int PositionHistoryId { get; set; }
        public int PositionId { get; set; }
        public string Action { get; set; }
        public string StatusFrom { get; set; }
        public string StatusTo { get; set; }
        public string AdditionalInfo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
