//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.EmployeePositions = new HashSet<EmployeePosition>();
            this.Positions = new HashSet<Position>();
            this.PositionHistories = new HashSet<PositionHistory>();
        }
    
        public int PositionId { get; set; }
        public int ReportToPositionId { get; set; }
        public string PositionNumber { get; set; }
        public int RolePositionDescriptionId { get; set; }
        public int UnitId { get; set; }
        public string PositionTitle { get; set; }
        public string Description { get; set; }
        public int PositionLevelId { get; set; }
        public int StatusId { get; set; }
        public string PositionPath { get; set; }
        public int LocationId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public string DivisionOverview { get; set; }
    
        public virtual CostCentreDetail CostCentreDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePosition> EmployeePositions { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
        public virtual Position ParentPosition { get; set; }
        public virtual PositionLevel PositionLevel { get; set; }
        public virtual RolePositionDescription RolePositionDescription { get; set; }
        public virtual StatusValue StatusValue { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionHistory> PositionHistories { get; set; }
        public virtual PositionInformation PositionInformation { get; set; }
    }
}
