//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PositionInformation()
        {
            this.PositionNotes = new HashSet<PositionNote>();
        }
    
        public int PositionId { get; set; }
        public string OlderPositionNumber3 { get; set; }
        public string OlderPositionNumber1 { get; set; }
        public string OlderPositionNumber2 { get; set; }
        public string SchNumber { get; set; }
        public string PositionTypeCode { get; set; }
        public string EmployeeTypeCode { get; set; }
        public Nullable<int> PositionNoteId { get; set; }
        public string TrimLink { get; set; }
        public Nullable<System.DateTime> PositionEndDate { get; set; }
        public double PositionFTE { get; set; }
        public string PositionStatusCode { get; set; }
        public string OccupationTypeCode { get; set; }
        public string OtherOverview { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual OccupationType OccupationType { get; set; }
        public virtual PositionStatusValue PositionStatusValue { get; set; }
        public virtual PositionType PositionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionNote> PositionNotes { get; set; }
        public virtual Position Position { get; set; }
    }
}
