//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleDescription()
        {
            this.KeyRelationships = new HashSet<KeyRelationship>();
            this.RoleCapabilities = new HashSet<RoleCapability>();
        }
    
        public int RoleDescriptionId { get; set; }
        public string Cluster { get; set; }
        public string SeniorExecutiveWorkLevelStandards { get; set; }
        public string ANZSCOCode { get; set; }
        public string PCATCode { get; set; }
        public string AgencyOverview { get; set; }
        public string Agency { get; set; }
        public string AgencyWebsite { get; set; }
        public string RolePrimaryPurpose { get; set; }
        public string KeyAccountabilities { get; set; }
        public string KeyChallenges { get; set; }
        public string DecisionMaking { get; set; }
        public string ReportingLine { get; set; }
        public string DirectReports { get; set; }
        public string BudgetExpenditure { get; set; }
        public string BudgetExpenditureValue { get; set; }
        public string BudgetExtraNotes { get; set; }
        public string EssentialRequirements { get; set; }
        public string RoleCapabilityItems { get; set; }
        public string CapabilitySummary { get; set; }
        public string FocusCapabilities { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string VersionStatus { get; set; }
        public string OldPDFileName { get; set; }
        public Nullable<bool> ManagerRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeyRelationship> KeyRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleCapability> RoleCapabilities { get; set; }
        public virtual RolePositionDescription RolePositionDescription { get; set; }
    }
}
