//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDescCapabilityMatrix
    {
        public string GradeCode { get; set; }
        public int Foundational_Min { get; set; }
        public int Foundational_Max { get; set; }
        public int Intermediate_Min { get; set; }
        public int Intermediate_Max { get; set; }
        public int Adept_Min { get; set; }
        public int Adept_Max { get; set; }
        public int Advanced_Min { get; set; }
        public int Advanced_Max { get; set; }
        public int HighlyAdvanced_Min { get; set; }
        public int HighlyAdvanced_Max { get; set; }
        public int FocusCapabilities_Min { get; set; }
        public int FocusCapabilities_Max { get; set; }
        public string Notes { get; set; }
    
        public virtual Grade Grade { get; set; }
    }
}
