//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.UnitList = new HashSet<Unit>();
            this.Positions = new HashSet<Position>();
        }
    
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitDescription { get; set; }
        public int BUnitId { get; set; }
        public int FunctionalAreaId { get; set; }
        public int ReportToUnit { get; set; }
        public int HierarchyId { get; set; }
        public int TeamTypeId { get; set; }
        public string UnitCustomClass { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual FunctionalArea FunctionalArea { get; set; }
        public virtual HierarchyLevel HierarchyLevel { get; set; }
        public virtual StatusValue StatusValue { get; set; }
        public virtual TeamType TeamType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> UnitList { get; set; }
        public virtual Unit ParentUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
    }
}
