//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doe.Ls.ProjectTemplate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfAction
    {
        public int WfActionId { get; set; }
        public string WfActionName { get; set; }
        public string WfActionStatus { get; set; }
        public string WfActionDescription { get; set; }
    }
}
