USE [C:\PROJECTS\GIT-DOE\DOE.LS.PROJECTTEMPLATE\DOE.LS.PROJECTTEMPLATE.CORE.TEST\APP_DATA\UNIT-TEST.MDF]
GO
DBCC SHRINKFILE (N'unit-test' , 0, TRUNCATEONLY)
GO
GO
DBCC SHRINKFILE (N'unit-test' , 17)
GO
