

SELECT COLUMN_NAME,'Select * from '+COL.TABLE_NAME +' where '+COL.COLUMN_NAME+'=-1' AS SQL , (SELECT TOP 1 system_type_id FROM sys.columns WHERE name=Col.COLUMN_NAME) AS Type
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS COL
WHERE OBJECTPROPERTY(OBJECT_ID(COL.CONSTRAINT_SCHEMA + '.' + QUOTENAME(COL.CONSTRAINT_NAME)), 'IsPrimaryKey') = 1 and (SELECT TOP 1 system_type_id FROM sys.columns WHERE name=Col.COLUMN_NAME)=56

union
SELECT COLUMN_NAME,'Select * from '+COL.TABLE_NAME +' where '+COL.COLUMN_NAME+'=''-1'''  , (SELECT TOP 1 system_type_id FROM sys.columns WHERE name=Col.COLUMN_NAME) AS Type
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS COL
WHERE OBJECTPROPERTY(OBJECT_ID(COL.CONSTRAINT_SCHEMA + '.' + QUOTENAME(COL.CONSTRAINT_NAME)), 'IsPrimaryKey') = 1 and (SELECT TOP 1 system_type_id FROM sys.columns WHERE name=Col.COLUMN_NAME)<>56


--SELECT * FROM sys.columns
--ORDER BY name

