// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Doe.Ls.ProjectTemplate.Data.T4Templates.MVCTemplate
{
    using Doe.Ls.EntityBase.Helper;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Data.Entity.Core.Metadata.Edm;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SingleView_partial_listTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            this.Write(" \r\n");
            this.Write("\r\n");
            
            #line 12 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
 T4Helper.SetAssemblyClassNameFormatFromContext(EntityContext); 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    
 
    var helper=new EdmMetadataHelper(EntityContext);
    

            
            #line default
            #line hidden
            this.Write("\r\n@model IEnumerable<");
            
            #line 21 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n@{    \r\n    ViewBagWrapper.InfoBag.SetTitle(\"");
            
            #line 23 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.Wordify(T4Helper.CleanClassName(EntityType.Name))));
            
            #line default
            #line hidden
            this.Write(@" List"",ViewData);
    var user = ViewBagWrapper.UserInfoExtensionBag.GetCurrentUser(ViewData);
    var task = ViewBagWrapper.TaskBag.GetCurrentTask(ViewData);
}


        <div class=""table-responsive"">
            <table class=""table table-striped table-condensed dt-responsive @*ajaxDataTable*@"" @*data-service=""");
            
            #line 30 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write("Service\" data-url=\"@Url.Action(\"ListJson\")\"*@>\r\n                @*<caption>");
            
            #line 31 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.Wordify(T4Helper.CleanClassName(EntityType.Name))));
            
            #line default
            #line hidden
            this.Write(" list</caption>*@\r\n                <thead>\r\n                    <tr>\r\n");
            
            #line 34 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    foreach (var property in T4Helper.ListPropertiesWithFkInfo(EntityType))
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    { 
            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 36 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
 if(property.FK){
            
            #line default
            #line hidden
            this.Write("              \r\n                        <th>\r\n                            @Html.D" +
                    "isplayNameFor(model => model.");
            
            #line 38 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PareEntityType.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n                        </th>\r\n          ");
            
            #line 40 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    } else{
            
            #line default
            #line hidden
            this.Write("           <th>\r\n                            @Html.DisplayNameFor(model => model." +
                    "");
            
            #line 42 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n                        </th>\r\n          ");
            
            #line 44 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("                       \r\n");
            
            #line 46 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write(@"                        <th class=""all""></th>
                    </tr>
                </thead>
                <tbody>
                    @* For ajax dataTable empty the tbody *@
                    @foreach (var item in Model) 
                    {
                       <tr>
");
            
            #line 55 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    foreach (var property in T4Helper.ListPropertiesWithFkInfo(EntityType))
            
            #line default
            #line hidden
            
            #line 56 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    {
    if (property == null)
    {
        continue;
    } 
            
            #line default
            #line hidden
            this.Write("                            <td>\r\n   ");
            
            #line 62 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
 if(property.FK){
            
            #line default
            #line hidden
            this.Write(" \r\n                                @Html.Raw(item.");
            
            #line 63 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PareEntityType.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 63 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.MetadataOperations.GetDispayPropertyName(property.PareEntityType)));
            
            #line default
            #line hidden
            this.Write(".StripHtml().Minimise(50))\r\n");
            
            #line 64 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
 continue;
           }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 67 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
if(T4Helper.PropertyOperations.IsRichText(property.Property, EntityType))
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        {
            
            #line default
            #line hidden
            this.Write("                                @Html.Raw(item.");
            
            #line 69 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Property.Name));
            
            #line default
            #line hidden
            this.Write(".StripHtml().Minimise(50))\r\n");
            
            #line 70 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        }
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        else if(T4Helper.PropertyOperations.IsDate(property.Property)||T4Helper.PropertyOperations.IsDateTime(property.Property)) 
            
            #line default
            #line hidden
            
            #line 72 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        {
            
            #line default
            #line hidden
            this.Write("                                @item.");
            
            #line 73 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Property.Name));
            
            #line default
            #line hidden
            this.Write(".ToEasyDateTimeFormat()\r\n");
            
            #line 74 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        }
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        else 
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        {
            
            #line default
            #line hidden
            this.Write("                                @Html.DisplayFor(modelItem => item.");
            
            #line 77 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 78 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
        }
            
            #line default
            #line hidden
            this.Write("                            </td>                       \r\n");
            
            #line 80 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("                            <td>\r\n                                <div class=\"btn" +
                    "-group-vertical\">\r\n                                    <a href=\"@Url.Action(\"Edi" +
                    "t\", new { ");
            
            #line 83 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 83 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetSingleKeyProperty(EntityType).Name));
            
            #line default
            #line hidden
            this.Write(" })\" class=\"btn btn-primary pop-up\"  data-toggle=\"modal\" data-target=\"#vlePluginM" +
                    "odal\">Edit</a>\r\n                                    <a href=\"@Url.Action(\"Detail" +
                    "s\", new { ");
            
            #line 84 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 84 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetSingleKeyProperty(EntityType).Name));
            
            #line default
            #line hidden
            this.Write(" })\" class=\"btn btn-primary pop-up\"  data-toggle=\"modal\" data-target=\"#vlePluginM" +
                    "odal\">Details</a>\r\n                                    <a href=\"@Url.Action(\"Del" +
                    "ete\", new { ");
            
            #line 85 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 85 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetSingleKeyProperty(EntityType).Name));
            
            #line default
            #line hidden
            this.Write(@" })"" class=""btn btn-primary pop-up""  data-toggle=""modal"" data-target=""#vlePluginModal"">Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 94 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"
    string GetKeyName()
    {
        return T4Helper.PropertyOperations.GetKeyLocalVariableName(EntityType);
    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_listTemplate.tt"

private string _AppNamespaceField;

/// <summary>
/// Access the AppNamespace parameter of the template.
/// </summary>
private string AppNamespace
{
    get
    {
        return this._AppNamespaceField;
    }
}

private global::System.Data.Entity.DbContext _EntityContextField;

/// <summary>
/// Access the EntityContext parameter of the template.
/// </summary>
private global::System.Data.Entity.DbContext EntityContext
{
    get
    {
        return this._EntityContextField;
    }
}

private global::System.Data.Entity.Core.Metadata.Edm.EntityType _EntityTypeField;

/// <summary>
/// Access the EntityType parameter of the template.
/// </summary>
private global::System.Data.Entity.Core.Metadata.Edm.EntityType EntityType
{
    get
    {
        return this._EntityTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool AppNamespaceValueAcquired = false;
if (this.Session.ContainsKey("AppNamespace"))
{
    this._AppNamespaceField = ((string)(this.Session["AppNamespace"]));
    AppNamespaceValueAcquired = true;
}
if ((AppNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AppNamespace");
    if ((data != null))
    {
        this._AppNamespaceField = ((string)(data));
    }
}
bool EntityContextValueAcquired = false;
if (this.Session.ContainsKey("EntityContext"))
{
    this._EntityContextField = ((global::System.Data.Entity.DbContext)(this.Session["EntityContext"]));
    EntityContextValueAcquired = true;
}
if ((EntityContextValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityContext");
    if ((data != null))
    {
        this._EntityContextField = ((global::System.Data.Entity.DbContext)(data));
    }
}
bool EntityTypeValueAcquired = false;
if (this.Session.ContainsKey("EntityType"))
{
    this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(this.Session["EntityType"]));
    EntityTypeValueAcquired = true;
}
if ((EntityTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityType");
    if ((data != null))
    {
        this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
