// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Doe.Ls.ProjectTemplate.Data.T4Templates.MVCTemplate
{
    using Doe.Ls.EntityBase.Helper;
    using System.Data.Entity.Core.Metadata.Edm;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SingleView_partial_update_Template : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("  \r\n");
            
            #line 10 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 T4Helper.SetAssemblyClassNameFormatFromContext(EntityContext); 
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
    var helper=new EdmMetadataHelper(EntityContext);
            
            #line default
            #line hidden
            this.Write("@using Doe.Ls.EntityBase.MVCExtensions\r\n@model ");
            
            #line 14 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write(@"
@{
    var user = ViewBagWrapper.UserInfoExtensionBag.GetCurrentUser(ViewData);
    var task = ViewBagWrapper.TaskBag.GetCurrentTask(ViewData); 
    var formMethod = ViewBagWrapper.FormOperations.GetFormMethod(ViewData);
    
    var formType = ViewBagWrapper.FormOperations.GetFormType(ViewData);
    var requestType = ViewBagWrapper.FormOperations.GetRequestType(ViewData);
    ");
            
            #line 22 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 var lookups=new List<string>();
    var suffix="";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
foreach (var mp in T4Helper.ListPropertiesWithFkInfo(EntityType)){
if(!mp.FK) continue;
        var parentItemName=T4Helper.GetLocalVariableName(mp.PareEntityType);
        if(lookups.Contains(parentItemName)){suffix=string.Format("{0}",lookups.IndexOf(parentItemName));}else{
        lookups.Add(parentItemName);
        }
        var localVariableName= T4Helper.GetLocalVariableName(mp.PareEntityType)+"Items"+suffix;

            
            #line default
            #line hidden
            this.Write("    var ");
            
            #line 32 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localVariableName));
            
            #line default
            #line hidden
            this.Write(" = ViewBagWrapper.ListBag.GetList(\"");
            
            #line 32 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localVariableName));
            
            #line default
            #line hidden
            this.Write("\",ViewData);\r\n");
            
            #line 33 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
    } 
            
            #line default
            #line hidden
            this.Write("    \r\n}\r\n@Html.AntiForgeryToken()\r\n");
            
            #line 36 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 foreach (var pm in T4Helper.ListPropertiesWithFkInfo(EntityType)) {  
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 ClearIndent(); 
            
            #line default
            #line hidden
            this.Write("      \r\n\r\n");
            
            #line 39 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
if(GenerateStaticTemplateForPrimaryKey(pm)){continue;} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 41 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
if(GenerateCheckBoxTemplate(pm)){continue;} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
if(GenerateSimpleInputTemplate(pm)){continue;} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 45 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
if(GenerateTextAreaTemplate(pm)){continue;} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 47 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
if(GenerateLookupTemplate(pm)){continue;} 
            
            #line default
            #line hidden
            this.Write("\r\n ");
            
            #line 49 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 }// foreach list of properties 
            
            #line default
            #line hidden
            this.Write(" \r\n  \r\n@functions\r\n{\r\n    bool IsKey(string propertyName) \r\n    {\r\n        var en" +
                    "tityType = ViewBagWrapper.EntityInfo.GetEntityType(ViewData);\r\n        return T4" +
                    "Helper.GetKeys(entityType).Any(p => p.Name == propertyName);\r\n    }\r\n\r\n    strin" +
                    "g ReadOnly(string propertyName) \r\n    {\r\n        var formType = ViewBagWrapper.F" +
                    "ormOperations.GetFormType(ViewData);\r\n        if (formType == FormType.Edit && I" +
                    "sKey(propertyName)) return \"readonly\";\r\n\r\n        var entityType = ViewBagWrappe" +
                    "r.EntityInfo.GetEntityType(ViewData);\r\n        \r\n        var prop = T4Helper.Get" +
                    "Property(propertyName, entityType);\r\n        var computedAttribute = T4Helper.Me" +
                    "tadataOperations.GetMetadataPropertyCustomAttribute<ComputedPropertyAttribute>(p" +
                    "rop, entityType);\r\n        if (computedAttribute == null) return string.Empty;\r\n" +
                    "\r\n        if (computedAttribute.ComputedPropertyType == ComputedPropertyType.Las" +
                    "tModifiedDate) return \"readonly\";\r\n        if (computedAttribute.ComputedPropert" +
                    "yType == ComputedPropertyType.LastModifiedUser) return \"readonly\";\r\n\r\n        if" +
                    " (computedAttribute.ComputedPropertyType == ComputedPropertyType.CreationDate) r" +
                    "eturn \"readonly\";\r\n        if (computedAttribute.ComputedPropertyType == Compute" +
                    "dPropertyType.CreatedUser) return \"readonly\";\r\n        \r\n        return string.E" +
                    "mpty;\r\n    }\r\n\r\n    string GetFormGroupClass(string propertyName) \r\n    {\r\n     " +
                    "   var entityType = ViewBagWrapper.EntityInfo.GetEntityType(ViewData);\r\n        " +
                    "var formType = ViewBagWrapper.FormOperations.GetFormType(ViewData);\r\n        var" +
                    " prop = T4Helper.GetProperty(propertyName, entityType);\r\n        var computedAtt" +
                    "ribute = T4Helper.MetadataOperations.GetMetadataPropertyCustomAttribute<Computed" +
                    "PropertyAttribute>(prop, entityType);\r\n        if (computedAttribute == null) re" +
                    "turn string.Empty;\r\n\r\n        if (computedAttribute.ComputedPropertyType == Comp" +
                    "utedPropertyType.LastModifiedDate) return \"hidden\";\r\n        if (computedAttribu" +
                    "te.ComputedPropertyType == ComputedPropertyType.LastModifiedUser) return \"hidden" +
                    "\";\r\n\r\n        if (computedAttribute.ComputedPropertyType == ComputedPropertyType" +
                    ".CreationDate) return \"hidden\";\r\n        if (computedAttribute.ComputedPropertyT" +
                    "ype == ComputedPropertyType.CreatedUser) return \"hidden\";\r\n\r\n        switch (for" +
                    "mType)\r\n        {\r\n            case FormType.Create:\r\n            {\r\n           " +
                    "     if (computedAttribute.ComputedPropertyType == ComputedPropertyType.Status) " +
                    "return \"hidden\";\r\n                if (computedAttribute.ComputedPropertyType == " +
                    "ComputedPropertyType.AutoIncrement) return \"hidden\";\r\n                if (comput" +
                    "edAttribute.ComputedPropertyType == ComputedPropertyType.Computed) return \"hidde" +
                    "n\";\r\n                break;\r\n            }\r\n        }\r\n        return string.Emp" +
                    "ty;        \r\n    }    \r\n}\r\n\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 110 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 
    //GenerateStaticTemplateForPrimaryKey
private bool GenerateStaticTemplateForPrimaryKey(PropMeta pm)
    {    
if(T4Helper.PropertyOperations.IsKey(pm.Property,EntityType) && T4Helper.PropertyOperations.IsKeyAutoIncrement(EntityType,EntityContext)) {
 
        
        #line default
        #line hidden
        
        #line 115 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("@Html.HiddenFor(model => model.");

        
        #line default
        #line hidden
        
        #line 116 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 116 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(")\r\n@if(formType==FormType.Edit)  {\r\n    <div class=\"form-group @GetFormGroupClass" +
        "(\"");

        
        #line default
        #line hidden
        
        #line 118 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 118 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\")\">\r\n        <label class=\"col-lg-4 \">@Html.DisplayNameFor(model => model.");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(") </label>\r\n        <div class=\"col-lg-8\">            <p class=\"form-control-plai" +
        "ntext\">@Html.DisplayFor(model => model.");

        
        #line default
        #line hidden
        
        #line 120 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 120 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(")</p>        </div>\r\n    </div>\r\n}                       \r\n");

        
        #line default
        #line hidden
        
        #line 123 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
         
            return true;

}

        
        #line default
        #line hidden
        
        #line 128 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
     
    return false;
}  
// end of GenerateStaticTemplateForPrimaryKey    

        
        #line default
        #line hidden
        
        #line 137 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 
    //GenerateSimpleInputTemplate
private bool GenerateSimpleInputTemplate(PropMeta pm)
    {    
if(!pm.FK&&T4Helper.IsFormInput(pm.Property,EntityType,EntityContext)) {
 
        
        #line default
        #line hidden
        
        #line 142 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" <div class=\"form-group @GetFormGroupClass(\"");

        
        #line default
        #line hidden
        
        #line 143 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 143 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\")\">\r\n  <label for=\"");

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" class=\"col-lg-4\">@Html.DisplayNameFor(model => model.");

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(") ");

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GetAsteriskForRequiredField(pm)));

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("</label>\r\n  <input type=\"");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GetInputType(pm)));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" name=\"");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" id=\"");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" class=\"form-control col-lg-8\" placeholder=\"e.g. ");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.Wordify(pm.Property.Name)));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" value=\"@Model.");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\"@ReadOnly(\"");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\")  ");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(IsRequired(pm)));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(SetEmail(pm)));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(SetDate(pm)));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("  ");

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(SetInteger(pm)));

        
        #line default
        #line hidden
        
        #line 145 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" /> \r\n</div>\r\n");

        
        #line default
        #line hidden
        
        #line 147 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
         
            return true;

}

        
        #line default
        #line hidden
        
        #line 152 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
     
    return false;
}  
// GenerateSimpleInputTemplate   

        
        #line default
        #line hidden
        
        #line 158 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 
    //GenerateTextAreaTemplate
private bool GenerateTextAreaTemplate(PropMeta pm)
    {    
if(!pm.FK&&T4Helper.PropertyOperations.IsTextArea(pm.Property,EntityType,EntityContext)) {
 
        
        #line default
        #line hidden
        
        #line 163 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" <div class=\"form-group @GetFormGroupClass(\"");

        
        #line default
        #line hidden
        
        #line 164 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 164 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\")\">\r\n  <label for=\"");

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" class=\"col-lg-4\">@Html.DisplayNameFor(model => model.");

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(") ");

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GetAsteriskForRequiredField(pm)));

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("</label>\r\n  <textarea name=\"");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" id=\"");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" class=\"form-control col-lg-8 ");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.PropertyOperations.IsRichText(pm.Property,EntityType)?"tinymce":string.Empty));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" placeholder=\"e.g. ");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.Wordify(pm.Property.Name)));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" ");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(SetRichText(pm)));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("  ");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(IsRequired(pm)));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("  >");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.PropertyOperations.IsRichText(pm.Property,EntityType)?"@Html.Raw(Model."+pm.Property.Name+")":"@Model."+pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("</textarea>\r\n</div>\r\n");

        
        #line default
        #line hidden
        
        #line 168 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
         
            return true;

}

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
     
    return false;
}  
// GenerateTextAreaTemplate   

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 
    //GenerateLookupTemplate
private bool GenerateLookupTemplate(PropMeta pm)
    {    
if(pm.FK) {
 
        
        #line default
        #line hidden
        
        #line 186 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" <div class=\"form-group @GetFormGroupClass(\"");

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\")\">\r\n  <label for=\"");

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" class=\"col-lg-4\">@Html.DisplayNameFor(model => model.");

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.PareEntityType.Name));

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(") ");

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GetAsteriskForRequiredField(pm)));

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("</label>\r\n  @Html.DropDownList(\"");

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(pm.PareEntityType)));

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("Items , \"Select ");

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.PareEntityType.Name.Wordify()));

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" ...\", new {id=\"");

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\", @class = \"form-control col-lg-8 select2picker\"");

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GetRequiredPropertyValue(pm)));

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(" })      \r\n</div>\r\n");

        
        #line default
        #line hidden
        
        #line 191 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
         
            return true;

}

        
        #line default
        #line hidden
        
        #line 196 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
     
    return false;
}  
// GenerateLookupTemplate   

        
        #line default
        #line hidden
        
        #line 204 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 
    //method with text template
private bool GenerateCheckBoxTemplate(PropMeta pm)
    {    
if(T4Helper.PropertyOperations.IsCheckbox(pm.Property)) {
 
        
        #line default
        #line hidden
        
        #line 209 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("  <div class=\"form-check\">\r\n            <label class=\"form-check-label\">\r\n       " +
        "         <input class=\"form-check-input\"  type=\"checkbox\" name=\"");

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" id=\"");

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" checked=\"@Model.");

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\" @ReadOnly(\"");

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\")/>\r\n            </label>\r\n        </div>    \r\n");

        
        #line default
        #line hidden
        
        #line 215 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
         
            return true;

}

        
        #line default
        #line hidden
        
        #line 220 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
     
    return false;
}  
// GenerateCheckBoxTemplate   

        
        #line default
        #line hidden
        
        #line 230 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
 
    //method with text template
private bool GenerateTemplate(PropMeta pm)
    {    
if(/*condition*/true) {
 
        
        #line default
        #line hidden
        
        #line 235 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("@Html.HiddenFor(model => model.");

        
        #line default
        #line hidden
        
        #line 236 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 236 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(")\r\n@if(formType==FormType.Edit)  {\r\n    <div class=\"form-group @GetFormGroupClass" +
        "(\"");

        
        #line default
        #line hidden
        
        #line 238 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 238 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write("\")\">\r\n        <label class=\"col-lg-4 \">@Html.DisplayNameFor(model => model.");

        
        #line default
        #line hidden
        
        #line 239 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 239 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(") </label>\r\n        <div class=\"col-lg-8\">            <p class=\"form-control-plai" +
        "ntext\">@Html.DisplayFor(model => model.");

        
        #line default
        #line hidden
        
        #line 240 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pm.Property.Name));

        
        #line default
        #line hidden
        
        #line 240 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
this.Write(")</p>        </div>\r\n    </div>\r\n}                       \r\n");

        
        #line default
        #line hidden
        
        #line 243 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
         
            return true;

}

        
        #line default
        #line hidden
        
        #line 248 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"
     
    return false;
}  
// GenerateTemplate   

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleView_partial_update_Template.tt"

private string _AppNamespaceField;

/// <summary>
/// Access the AppNamespace parameter of the template.
/// </summary>
private string AppNamespace
{
    get
    {
        return this._AppNamespaceField;
    }
}

private global::System.Data.Entity.DbContext _EntityContextField;

/// <summary>
/// Access the EntityContext parameter of the template.
/// </summary>
private global::System.Data.Entity.DbContext EntityContext
{
    get
    {
        return this._EntityContextField;
    }
}

private global::System.Data.Entity.Core.Metadata.Edm.EntityType _EntityTypeField;

/// <summary>
/// Access the EntityType parameter of the template.
/// </summary>
private global::System.Data.Entity.Core.Metadata.Edm.EntityType EntityType
{
    get
    {
        return this._EntityTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool AppNamespaceValueAcquired = false;
if (this.Session.ContainsKey("AppNamespace"))
{
    this._AppNamespaceField = ((string)(this.Session["AppNamespace"]));
    AppNamespaceValueAcquired = true;
}
if ((AppNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AppNamespace");
    if ((data != null))
    {
        this._AppNamespaceField = ((string)(data));
    }
}
bool EntityContextValueAcquired = false;
if (this.Session.ContainsKey("EntityContext"))
{
    this._EntityContextField = ((global::System.Data.Entity.DbContext)(this.Session["EntityContext"]));
    EntityContextValueAcquired = true;
}
if ((EntityContextValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityContext");
    if ((data != null))
    {
        this._EntityContextField = ((global::System.Data.Entity.DbContext)(data));
    }
}
bool EntityTypeValueAcquired = false;
if (this.Session.ContainsKey("EntityType"))
{
    this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(this.Session["EntityType"]));
    EntityTypeValueAcquired = true;
}
if ((EntityTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityType");
    if ((data != null))
    {
        this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
