// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Doe.Ls.ProjectTemplate.Data.T4Templates.MVCTemplate
{
    using Doe.Ls.EntityBase.Helper;
    using Doe.Ls.EntityBase.MVCExtensions;
    using System.Data.Entity.Core.Metadata.Edm;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SingleControllerTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("  \r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 15 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    

    var helper=new EdmMetadataHelper(EntityContext);
    var repName = T4Helper.CleanClassName(EntityType.Name) + "Repository";
    var cleanName = T4Helper.CleanClassName(EntityType.Name);    

            
            #line default
            #line hidden
            this.Write(@"using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using Doe.Ls.EntityBase.Models;
using Doe.Ls.EntityBase.Helper;
using Doe.Ls.EntityBase.Logging;
using ");
            
            #line 33 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppNamespace));
            
            #line default
            #line hidden
            this.Write(".Core.BL;\r\nusing ");
            
            #line 34 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppNamespace));
            
            #line default
            #line hidden
            this.Write(".Core.BL.EntityRepositories;\r\nusing ");
            
            #line 35 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppNamespace));
            
            #line default
            #line hidden
            this.Write(".Core.BL.UI;\r\nusing ");
            
            #line 36 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppNamespace));
            
            #line default
            #line hidden
            this.Write(".Core.BL.Models.Light;\r\nusing ");
            
            #line 37 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppNamespace));
            
            #line default
            #line hidden
            this.Write(".Data;\r\nusing ");
            
            #line 38 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppNamespace));
            
            #line default
            #line hidden
            this.Write(".Web.Controllers.Domain;\r\n\r\nnamespace ");
            
            #line 40 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppNamespace));
            
            #line default
            #line hidden
            this.Write(".Web.Controllers\r\n{\r\n");
            
            #line 42 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    if(T4Helper.MetadataOperations.HasAnyRichText(EntityType))
    {PushIndent(" "); 
            
            #line default
            #line hidden
            this.Write("[ValidateInput(false)]");
            
            #line 43 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("    \r\n    ");
            
            #line 44 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    if(T4Helper.MetadataOperations.IsSecure(EntityType))
    {PushIndent(" "); 
            
            #line default
            #line hidden
            this.Write("[System.Web.Mvc.Authorize(Roles=\"");
            
            #line 45 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.MetadataOperations.AccessRoles(EntityType)));
            
            #line default
            #line hidden
            this.Write("\")]");
            
            #line 45 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("    \r\n    public partial class ");
            
            #line 46 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("Controller : AppControllerBase\r\n    {\r\n     private ");
            
            #line 48 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("Repository _repository=null;\r\n     public ");
            
            #line 49 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("Repository Repository\r\n         {\r\n         get\r\n         {\r\n\r\n             retur" +
                    "n _repository=_repository ?? ServiceRepository.");
            
            #line 54 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("Repository();\r\n\r\n             }\r\n \r\n         }\r\n                \r\n\r\n        publi" +
                    "c ActionResult Index()\r\n        {\r\n            var ");
            
            #line 63 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write("s = Repository.List();\r\n            return View(");
            
            #line 64 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write("s.ToList());\r\n        }\r\n\r\n        //\r\n        // GET: /");
            
            #line 68 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("/Details/5\r\n        public ActionResult Details(");
            
            #line 69 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 69 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 69 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDefaultValue()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ViewBagWrapper.FormOperations.SetFormType(FormType.Deta" +
                    "ils, ViewData);\r\n            var ");
            
            #line 72 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" = Repository.GetEntityByKey(");
            
            #line 72 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(");\r\n            if (");
            
            #line 73 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                throw new HttpException(\"");
            
            #line 75 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" not found\");\r\n            }\r\n             if (Request.IsAjaxRequest()) {\r\n      " +
                    "            return View(\"Details-modal\", ");
            
            #line 78 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n              } else {\r\n            return View(");
            
            #line 80 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(@");
              }

            
        }

         public ActionResult ListJson([FromUri] JQueryDataTableParamModel arg) 
         {
            InitialiseArgument(arg);
            var dataTableResult = new DataTableResult();
         
            try
            {
                var ");
            
            #line 93 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write("s = Repository.List();\r\n                IQueryable<");
            
            #line 94 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("> displayed");
            
            #line 94 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s;\r\n            \r\n                if (!string.IsNullOrWhiteSpace(arg.sSearch))\r\n " +
                    "               {\r\n                    var searchArgs = new SearchArg { Search = " +
                    "arg.sSearch };\r\n                    displayed");
            
            #line 99 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s = Repository.Filter");
            
            #line 99 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s(");
            
            #line 99 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write("s, searchArgs);\r\n                }\r\n                else\r\n                {\r\n    " +
                    "                displayed");
            
            #line 103 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s = CustomOrderBy.CustomSort(");
            
            #line 103 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write("s, arg);\r\n                }\r\n\r\n                var totalRecord =  displayed");
            
            #line 106 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s.Count();\r\n                var totalDisplayRecord =  displayed");
            
            #line 107 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s.Count();\r\n\r\n                if (arg.iDisplayLength == -1)\r\n                    " +
                    "arg.iDisplayLength = totalRecord;\r\n\r\n                displayed");
            
            #line 112 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s =  displayed");
            
            #line 112 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s.Skip(arg.iDisplayStart).Take(arg.iDisplayLength);\r\n\r\n                var result" +
                    " = displayed");
            
            #line 114 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("s.AsEnumerable().ToArray().Select(ent => ent.To(new ");
            
            #line 114 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name.CleanEntityName()));
            
            #line default
            #line hidden
            this.Write(@"Light()));

                dataTableResult.sEcho = arg.sEcho;
                dataTableResult.iTotalRecords = totalRecord;
                dataTableResult.iTotalDisplayRecords = totalDisplayRecord;
                dataTableResult.aaData = result;
                dataTableResult.Status= Status.Success;
                dataTableResult.Message = ""Success"";               
            } 
            catch (Exception exception) 
            {
                LogException(exception);

                dataTableResult.Status = Status.Error;
                dataTableResult.Message = ""Errors"";
                dataTableResult.AddError(new DbValidationError(""DB error"",
                    ""Oops! something wrong happened "" + exception.Message));
            }

            return Json(dataTableResult, JsonRequestBehavior.AllowGet);
        }

         // GET: /");
            
            #line 136 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("/Details/5\r\n        public ActionResult DetailsJson(");
            
            #line 137 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 137 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 137 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDefaultValue()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var ajaxResult = new Result();\r\n            \r\n         " +
                    "   try {\r\n                var ");
            
            #line 142 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write("Light = Repository.GetEntityByKey(");
            
            #line 142 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(").To(new ");
            
            #line 142 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("Light());\r\n                \r\n\r\n                ajaxResult.Status = Status.Success" +
                    ";\r\n                ajaxResult.Message = \"Success\";\r\n                ajaxResult.D" +
                    "ata = ");
            
            #line 147 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(@"Light;

                return Json(ajaxResult, JsonRequestBehavior.AllowGet);
            } catch (Exception exception) {
                LogException(exception);
                ajaxResult.Status = Status.Error;
                ajaxResult.Message = ""Errors"";
                ajaxResult.AddError(new DbValidationError(""DB error"",
                    ""Oops! something wrong happened "" + exception.Message));
                return Json(ajaxResult, JsonRequestBehavior.AllowGet);
            }
            
        }



        // GET: /");
            
            #line 163 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n        public ActionResult Delete(");
            
            #line 164 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 164 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 164 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDefaultValue()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ViewBagWrapper.FormOperations.SetFormType(FormType.Dele" +
                    "te, ViewData);\r\n\r\n            var ");
            
            #line 168 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" = Repository.GetEntityByKey(");
            
            #line 168 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(");\r\n            if (");
            
            #line 169 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                throw new HttpException(\"");
            
            #line 171 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" not found\");\r\n            }\r\n             if (Request.IsAjaxRequest()) {\r\n      " +
                    "            return View(\"Delete-modal\", ");
            
            #line 174 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n              } else {\r\n            return View(");
            
            #line 176 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n              }\r\n\r\n            \r\n        }\r\n        //\r\n        // GET: /");
            
            #line 182 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write(@"/Create
        public ActionResult Create()
        {
            ViewBagWrapper.FormOperations.SetNullModel(true,ViewData);
            ViewBagWrapper.FormOperations.SetFormType(FormType.Create, ViewData);
            CreateLookups();
            if (Request.IsAjaxRequest()) {
                return View(""Create-modal"", new ");
            
            #line 189 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("());\r\n            } else {\r\n            return View(new ");
            
            #line 191 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("());\r\n            }\r\n        }\r\n\r\n        //\r\n        // POST: /");
            
            #line 196 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n\r\n        [System.Web.Mvc.HttpPost]\r\n        [ValidateAntiForgeryToken]\r" +
                    "\n        public ActionResult Create(");
            
            #line 200 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 200 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ");
            
            #line 202 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelStateCode(FormType.Create)));
            
            #line default
            #line hidden
            this.Write(@"
            
            ViewBagWrapper.FormOperations.SetFormType(FormType.Create, ViewData);
            var ajaxResult = new Result();
            var errors = Repository.GetValidationErrors(ModelState).ToList();
            if (ModelState.IsValid) {
                try {
                    Repository.Insert(");
            
            #line 209 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n                } catch (Exception exception) {\r\n                    LogExcep" +
                    "tion(exception);\r\n                    errors.AddRange(Repository.GetBackendValid" +
                    "ationErrors());\r\n                    errors.Add(new DbValidationError(\"DB error\"" +
                    ",  \"Oops! something wrong happened \"+exception.Message));\r\n\r\n                   " +
                    " if ((Request.IsAjaxRequest())) {\r\n                        ajaxResult.Status = S" +
                    "tatus.Error;\r\n                        ajaxResult.Message = \"Errors\";\r\n          " +
                    "              ajaxResult.AddErrors(errors);\r\n                        return Json" +
                    "(ajaxResult);\r\n                    } else {\r\n                        \r\n         " +
                    "               ViewBagWrapper.ErrorBag.SetErrors(errors, ViewData);\r\n           " +
                    "         }\r\n                   \r\n                }\r\n                CreateLookup" +
                    "s();\r\n                if (Request.IsAjaxRequest()) {\r\n                    ajaxRe" +
                    "sult.Status = Status.Success;\r\n                    ajaxResult.Message = \"Success" +
                    "\";\r\n                    return Json(ajaxResult);\r\n                } \r\n          " +
                    "      return RedirectToAction(\"Index\");               \r\n             \r\n  }\r\n    " +
                    "        else\r\n            {\r\n                if (Request.IsAjaxRequest())\r\n     " +
                    "           {\r\n                    ajaxResult.Status = Status.Error;\r\n           " +
                    "         ajaxResult.Message = \"Errors\";\r\n                    ajaxResult.AddError" +
                    "s(errors);\r\n                    return Json(ajaxResult);\r\n                }\r\n   " +
                    "             else\r\n                {\r\n                    ViewBagWrapper.ErrorBa" +
                    "g.SetErrors(Repository.GetValidationErrors(ModelState), ViewData);\r\n            " +
                    "        CreateLookups();\r\n                    return View(");
            
            #line 248 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n                \r\n            }\r\n            \r\n        }\r\n" +
                    "\r\n              \r\n        //\r\n        // GET: /");
            
            #line 257 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n        public ActionResult Edit(");
            
            #line 258 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyType()));
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 258 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 258 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDefaultValue()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ViewBagWrapper.FormOperations.SetFormType(FormType.Edit" +
                    ", ViewData);\r\n            var ");
            
            #line 261 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" = Repository.GetEntityByKey(");
            
            #line 261 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetKeyName()));
            
            #line default
            #line hidden
            this.Write(");\r\n            if (");
            
            #line 262 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                throw new HttpException(\"");
            
            #line 264 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(" not found\");\r\n            }\r\n            CreateLookups();\r\n            \r\n       " +
                    "       if (Request.IsAjaxRequest()) {\r\n                  return View(\"Edit-modal" +
                    "\", ");
            
            #line 269 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n              } else {\r\n                  return View(");
            
            #line 271 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n              }\r\n        }\r\n\r\n        //\r\n        // POST: /");
            
            #line 276 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n        [System.Web.Mvc.HttpPost]\r\n        [ValidateAntiForgeryToken]\r\n " +
                    "       public ActionResult Edit(");
            
            #line 279 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 279 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ");
            
            #line 281 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelStateCode(FormType.Edit)));
            
            #line default
            #line hidden
            this.Write(@"
            ViewBagWrapper.FormOperations.SetFormType(FormType.Edit, ViewData);
            var ajaxResult = new Result();
            var errors = Repository.GetValidationErrors(ModelState).ToList();
            
            if (ModelState.IsValid)
            {
                var old");
            
            #line 288 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write(" = Repository.GetEntityByEntityKey(");
            
            #line 288 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n                \r\n                Repository.SetPropertyValuesFrom(ref old");
            
            #line 290 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 290 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n                try\r\n                {\r\n                    Repository.Upda" +
                    "te(old");
            
            #line 294 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write(");     \r\n                } \r\n                catch (Exception exception) \r\n      " +
                    "          {\r\n                    LogException(exception);\r\n                    e" +
                    "rrors.AddRange(Repository.GetBackendValidationErrors());\r\n                    er" +
                    "rors.Add(new DbValidationError(\"DB error\",  \"Oops! something wrong happened \"+ex" +
                    "ception.Message));\r\n\r\n                    if ((Request.IsAjaxRequest())) \r\n     " +
                    "               {\r\n                        ajaxResult.Status = Status.Error;\r\n   " +
                    "                     ajaxResult.Message = \"Errors\";\r\n                        aja" +
                    "xResult.AddErrors(errors);\r\n                        return Json(ajaxResult);\r\n  " +
                    "                  } \r\n                    else \r\n                    {          " +
                    "              \r\n                        ViewBagWrapper.ErrorBag.SetErrors(errors" +
                    ", ViewData);\r\n                    }\r\n                   \r\n                }\r\n\r\n " +
                    "               CreateLookups();\r\n\r\n                if (Request.IsAjaxRequest()) " +
                    "\r\n                {\r\n                    ajaxResult.Status = Status.Success;\r\n  " +
                    "                  ajaxResult.Message = \"Success\";\r\n\r\n                    return " +
                    "Json(ajaxResult);\r\n                } \r\n                return RedirectToAction(\"" +
                    "Index\");\r\n            }\r\n            else\r\n            {\r\n                if (Re" +
                    "quest.IsAjaxRequest())\r\n                {\r\n                    ajaxResult.Status" +
                    " = Status.Error;\r\n                    ajaxResult.Message = \"Errors\";\r\n          " +
                    "          ajaxResult.AddErrors(errors);\r\n                    return Json(ajaxRes" +
                    "ult);\r\n                }\r\n                else\r\n                {\r\n             " +
                    "       ViewBagWrapper.ErrorBag.SetErrors(Repository.GetValidationErrors(ModelSta" +
                    "te), ViewData);\r\n                    CreateLookups();\r\n                    retur" +
                    "n View(");
            
            #line 340 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n                }                \r\n            }          \r\n        }\r\n\r\n    " +
                    "    //\r\n        // POST: /");
            
            #line 346 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n\r\n        [System.Web.Mvc.HttpPost, System.Web.Mvc.ActionName(\"Delete\"" +
                    ")]\r\n        [ValidateAntiForgeryToken]\r\n        public ActionResult DeleteConfir" +
                    "med(");
            
            #line 350 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 350 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ViewBagWrapper.FormOperations.SetFormType(FormType.Dele" +
                    "te, ViewData);\r\n            var ajaxResult = new Result();            \r\n        " +
                    "    var old");
            
            #line 354 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write(" = Repository.GetEntityByEntityKey(");
            
            #line 354 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(EntityType)));
            
            #line default
            #line hidden
            this.Write(");\r\n            try\r\n            {\r\n                Repository.Delete(old");
            
            #line 357 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cleanName));
            
            #line default
            #line hidden
            this.Write(@");     
            }
            catch (Exception exception)
            {
                LogException(exception);
            
                var errors = Repository.GetBackendValidationErrors().ToList();
                errors.Add(new DbValidationError(""DB error"",  ""Oops! something wrong happened ""+exception.Message));

                if ((Request.IsAjaxRequest())) 
                {
                    ajaxResult.Status = Status.Error;
                    ajaxResult.Message = ""Errors"";
                    ajaxResult.AddErrors(errors);
                    
                    return Json(ajaxResult);
                }
                else
                {
                    ViewBagWrapper.ErrorBag.SetErrors(errors, ViewData);
                }
                   
            }

            CreateLookups();
        
            if (Request.IsAjaxRequest()) 
            {
                ajaxResult.Status = Status.Success;
                ajaxResult.Message = ""Success"";
            
                return Json(ajaxResult);
            } 
        
            return RedirectToAction(""Index"");
        }
        
        private void CreateLookups() 
        {        
        
        var enity = T4Helper.GetEntityType(""");
            
            #line 397 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityType.Name));
            
            #line default
            #line hidden
            this.Write("\", this.ServiceRepository.GetUnitOfWork().DbContext);\r\n        ViewBagWrapper.Ent" +
                    "ityInfo.SetEntityType(enity,ViewData);        \r\n  ");
            
            #line 399 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    var lookups=new List<string>();
    var suffix="";
    
   
            
            #line default
            #line hidden
            this.Write("            \r\n");
            
            #line 404 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    foreach (var mp in T4Helper.ListPropertiesWithFkInfo(EntityType))
    {
        if(!mp.FK)continue;
        var parentItemName=T4Helper.GetLocalVariableName(mp.PareEntityType);
        if(lookups.Contains(parentItemName)){suffix=string.Format("{0}",lookups.IndexOf(parentItemName));}else{
            lookups.Add(parentItemName);
        }
        var localVariableName= T4Helper.GetLocalVariableName(mp.PareEntityType)+"Items"+suffix;


            
            #line default
            #line hidden
            this.Write("        var ");
            
            #line 414 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localVariableName));
            
            #line default
            #line hidden
            this.Write("=ServiceRepository.");
            
            #line 414 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.CleanClassName(mp.PareEntityType.Name)));
            
            #line default
            #line hidden
            this.Write("Repository()\r\n                    .List().ToArray()\r\n                    .Select(" +
                    "pe => new SelectListItemExtension { Value = pe.");
            
            #line 416 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mp.FkProperty.Name));
            
            #line default
            #line hidden
            this.Write(".ToString(), Text =");
            
            #line 416 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetLookupText(mp.PareEntityType,"pe")));
            
            #line default
            #line hidden
            this.Write("})\r\n                    .ToArray();\r\n        \r\n        ViewBagWrapper.ListBag.Set" +
                    "List(\"");
            
            #line 419 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localVariableName));
            
            #line default
            #line hidden
            this.Write("\",");
            
            #line 419 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetLocalVariableName(mp.PareEntityType)));
            
            #line default
            #line hidden
            this.Write("Items,ViewData);\r\n                \r\n\r\n  ");
            
            #line 422 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n               \r\n        \r\n        protected override void Dispose(b" +
                    "ool disposing)\r\n        {\r\n\r\n            base.Dispose(disposing);\r\n        }\r\n  " +
                    "  }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 433 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    string GetKeyType()
    {
        if (T4Helper.PropertyOperations.IsKeyString(this.EntityType))
        {
            return "string";
        }
        return "int";
    } 
        
        #line default
        #line hidden
        
        #line 442 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    string GetKeyName()
    {
        return T4Helper.PropertyOperations.GetKeyLocalVariableName(EntityType);

    } 
        
        #line default
        #line hidden
        
        #line 449 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    string GetDefaultValue()
    {
        if (T4Helper.PropertyOperations.IsKeyString(this.EntityType))
        {
            return "= \"\"";
        }
        return "= 0";
    } 
        
        #line default
        #line hidden
        
        #line 458 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    string ModelStateCode(FormType formType)
    {
        var sb = new StringBuilder();

        foreach (var property in this.EntityType.Properties)
        {
        if (T4Helper.PropertyOperations.IsBoolean(property, EntityType))
            {
                sb.Append(ReplaceOnFieldWithBooleanPropertyStateCode(property));
            }
            
            var computedAttribute = T4Helper.MetadataOperations.GetMetadataPropertyCustomAttribute<ComputedPropertyAttribute>(property, EntityType);
            if (computedAttribute == null) continue;

            if (computedAttribute.ComputedPropertyType == ComputedPropertyType.LastModifiedDate)sb.Append(RemovePropertyFromStateCode(property));
        
            if (computedAttribute.ComputedPropertyType == ComputedPropertyType.LastModifiedUser) sb.Append(RemovePropertyFromStateCode(property));

            if (computedAttribute.ComputedPropertyType == ComputedPropertyType.CreationDate) sb.Append(RemovePropertyFromStateCode(property));
            if (computedAttribute.ComputedPropertyType == ComputedPropertyType.CreatedUser) sb.Append(RemovePropertyFromStateCode(property));

            switch (formType)
            {
                case FormType.Create:
                {
                    if (computedAttribute.ComputedPropertyType == ComputedPropertyType.Status) sb.Append(RemovePropertyFromStateCode(property));
                    if (computedAttribute.ComputedPropertyType == ComputedPropertyType.AutoIncrement) sb.Append(RemovePropertyFromStateCode(property));
                    if (computedAttribute.ComputedPropertyType == ComputedPropertyType.Computed) sb.Append(RemovePropertyFromStateCode(property));
                
                    break;
                }
            }
            
        }
        
        return sb.ToString();
    } 
        
        #line default
        #line hidden
        
        #line 498 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    string RemovePropertyFromStateCode(EdmProperty property)
{
return String.Format("this.ModelState.Remove(\"{0}\"); \n\r",property.Name);

} 
        
        #line default
        #line hidden
        
        #line 506 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    string ReplaceOnFieldWithBooleanPropertyStateCode(EdmProperty property)
{
  var localVar = T4Helper.GetLocalVariableName(this.EntityType);
    var sb = new StringBuilder();
        sb.Append(String.Format("this.ModelState.Remove(\"{0}\"); \n\r",property.Name));
        sb.Append(String.Format("{0}.{1} = Request[\"{1}\"].IsOn();",localVar,property.Name));
    return sb.ToString();


} 
        
        #line default
        #line hidden
        
        #line 518 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"
    string GetLookupText(System.Data.Entity.Core.Metadata.Edm.EntityType  entityType,string parameter)
    {
    if (entityType.Name=="DocumentType")
    {
        
    }
        var att = T4Helper.PropertyOperations.GetDispayPropertyAttribute(entityType);
        var propertyName = T4Helper.PropertyOperations.GetDispayPropertyName(entityType);
    

    if (att == null || !att.Computed)
    {
    var prop = T4Helper.GetProperty(propertyName, entityType);

        if (prop == null)
        {
            throw new InvalidOperationException(String.Format("property {0} is not {1} members please Fix the metadata attributes for {1}",propertyName,entityType));
        }
        if (T4Helper.PropertyOperations.IsRichText(prop,entityType))
        {
            return parameter + "." + propertyName+".StripHtml()";
        }    
        return parameter + "." + propertyName;

    }

        return att.Formula.Replace("{0}", parameter);
    
    } 
        
        #line default
        #line hidden
        
        #line 1 "C:\Users\det\Source\Repos\Doe.Ls.ProjectTemplateMini\Doe.Ls.ProjectTemplate.Data\T4Templates\MVCTemplate\SingleControllerTemplate.tt"

private string _AppNamespaceField;

/// <summary>
/// Access the AppNamespace parameter of the template.
/// </summary>
private string AppNamespace
{
    get
    {
        return this._AppNamespaceField;
    }
}

private global::System.Data.Entity.DbContext _EntityContextField;

/// <summary>
/// Access the EntityContext parameter of the template.
/// </summary>
private global::System.Data.Entity.DbContext EntityContext
{
    get
    {
        return this._EntityContextField;
    }
}

private global::System.Data.Entity.Core.Metadata.Edm.EntityType _EntityTypeField;

/// <summary>
/// Access the EntityType parameter of the template.
/// </summary>
private global::System.Data.Entity.Core.Metadata.Edm.EntityType EntityType
{
    get
    {
        return this._EntityTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool AppNamespaceValueAcquired = false;
if (this.Session.ContainsKey("AppNamespace"))
{
    this._AppNamespaceField = ((string)(this.Session["AppNamespace"]));
    AppNamespaceValueAcquired = true;
}
if ((AppNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AppNamespace");
    if ((data != null))
    {
        this._AppNamespaceField = ((string)(data));
    }
}
bool EntityContextValueAcquired = false;
if (this.Session.ContainsKey("EntityContext"))
{
    this._EntityContextField = ((global::System.Data.Entity.DbContext)(this.Session["EntityContext"]));
    EntityContextValueAcquired = true;
}
if ((EntityContextValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityContext");
    if ((data != null))
    {
        this._EntityContextField = ((global::System.Data.Entity.DbContext)(data));
    }
}
bool EntityTypeValueAcquired = false;
if (this.Session.ContainsKey("EntityType"))
{
    this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(this.Session["EntityType"]));
    EntityTypeValueAcquired = true;
}
if ((EntityTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityType");
    if ((data != null))
    {
        this._EntityTypeField = ((global::System.Data.Entity.Core.Metadata.Edm.EntityType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
